apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedcuda-deployment-vk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedcuda-vk
  template:
    metadata:
      labels:
        app: fedcuda-vk
    spec:
      nodeSelector:
        key: vk
      containers:
      - name: fedcuda-vk
        image: dwnusa/fedcuda:v0.2
        ports:
          - containerPort: 22
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: fedcuda-volume
          mountPath: /root/data
      volumes:
      - name: fedcuda-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-vk
