apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedcuda-deployment-vj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fedcuda-vj
  template:
    metadata:
      labels:
        app: fedcuda-vj
    spec:
      nodeSelector:
        key: vj
      containers:
      - name: fedcuda-vj
        image: dwnusa/fedcuda:v0.1
        ports:
          - containerPort: 22
