---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fedcuda-pv-vk
  labels:
    type: local
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home2/ksyint1111/2024_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedcuda-pvc-vk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: manual
  selector:
    matchLabels:
      type: local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedcuda-deployment-vk30023
  annotations:
    kubernetes.io/change-cause: "vj30022 -> vk30023"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedcuda-vk30023
  template:
    metadata:
      labels:
        app: fedcuda-vk30023
    spec:
      nodeSelector:
        key: vk
      containers:
      - name: fedcuda-vk30023
        image: dwnusa/fedcuda:v0.2
        ports:
          - containerPort: 22
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: fedcuda-volume
          mountPath: /root/data
      volumes:
      - name: fedcuda-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-vk
---
apiVersion: v1
kind: Service
metadata:
  name: fedcuda-nodeport-vk30023
spec:
  type: NodePort
  selector:
    app: fedcuda-vk30023
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30023
