---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fedcuda-pv-vd
  labels:
    type: local
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home2/dwnusa/2024_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedcuda-pvc-vd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: manual
  selector:
    matchLabels:
      type: local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedcuda-deployment-vd30021
  annotations:
    kubernetes.io/change-cause: "vd -> vd30021"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedcuda-vd30021
  template:
    metadata:
      labels:
        app: fedcuda-vd30021
    spec:
      nodeSelector:
        key: vd
      containers:
      - name: fedcuda-vd30021
        image: dwnusa/fedcuda:v0.3
        ports:
          - containerPort: 22
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: fedcuda-volume
          mountPath: /root/data
      volumes:
      - name: fedcuda-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-vd
---
apiVersion: v1
kind: Service
metadata:
  name: fedcuda-nodeport-vd30021
spec:
  type: NodePort
  selector:
    app: fedcuda-vd30021
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30021
