apiVersion: v1
kind: PersistentVolume
metadata:
  name: fedcuda-pv-vd
  labels:
    type: local
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home2/dwnusa/2024_data
