apiVersion: v1
kind: Service
metadata:
  name: ssh-server-nodeport-vd
spec:
  type: NodePort
  selector:
    app: ssh-server-vd
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30021
