apiVersion: v1
kind: PersistentVolume
metadata:
  name: freesurfer-license-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home2/dwnusa/2024_data/.license
    type: File

