---
apiVersion: batch/v1
kind: Job
metadata:
  name: freesurfer-recon-all-job-${LBL}-${IDX1}
spec:
  template:
    spec:
      nodeSelector:
        key: ${LBL}
      containers:
      - name: freesurfer-container
        image: freesurfer/freesurfer:7.2.0
        command: ["/bin/bash", "-c", "mkdir -p /root/data/FREESURFER/FREESURFER_OUTDIR; source /usr/local/freesurfer/SetUpFreeSurfer.sh; recon-all -subjid ${IDX1} -i /root/data/FREESURFER/OUTDIR/${IDX1}.nii.gz -sd /root/data/FREESURFER/FREESURFER_OUTDIR -all"]
        resources:
          requests:
            cpu: "3800m"
          limits:
            cpu: "4000m"
        volumeMounts:
        - name: license-volume
          mountPath: /usr/local/freesurfer/.license
        - name: data-volume
          mountPath: /root/data
      restartPolicy: Never
      volumes:
      - name: license-volume
        hostPath:
          path: /home2/${USR}/2024_data/FREESURFER/.license
          type: File
      - name: data-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-${LBL}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: freesurfer-recon-all-job-${LBL}-${IDX2}
spec:
  template:
    spec:
      nodeSelector:
        key: ${LBL}
      containers:
      - name: freesurfer-container
        image: freesurfer/freesurfer:7.2.0
        command: ["/bin/bash", "-c", "mkdir -p /root/data/FREESURFER/FREESURFER_OUTDIR; source /usr/local/freesurfer/SetUpFreeSurfer.sh; recon-all -subjid ${IDX2} -i /root/data/FREESURFER/OUTDIR/${IDX2}.nii.gz -sd /root/data/FREESURFER/FREESURFER_OUTDIR -all"]
        resources:
          requests:
            cpu: "3800m"
          limits:
            cpu: "4000m"
        volumeMounts:
        - name: license-volume
          mountPath: /usr/local/freesurfer/.license
        - name: data-volume
          mountPath: /root/data
      restartPolicy: Never
      volumes:
      - name: license-volume
        hostPath:
          path: /home2/${USR}/2024_data/FREESURFER/.license
          type: File
      - name: data-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-${LBL}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: freesurfer-recon-all-job-${LBL}-${IDX3}
spec:
  template:
    spec:
      nodeSelector:
        key: ${LBL}
      containers:
      - name: freesurfer-container
        image: freesurfer/freesurfer:7.2.0
        command: ["/bin/bash", "-c", "mkdir -p /root/data/FREESURFER/FREESURFER_OUTDIR; source /usr/local/freesurfer/SetUpFreeSurfer.sh; recon-all -subjid ${IDX3} -i /root/data/FREESURFER/OUTDIR/${IDX3}.nii.gz -sd /root/data/FREESURFER/FREESURFER_OUTDIR -all"]
        resources:
          requests:
            cpu: "3800m"
          limits:
            cpu: "4000m"
        volumeMounts:
        - name: license-volume
          mountPath: /usr/local/freesurfer/.license
        - name: data-volume
          mountPath: /root/data
      restartPolicy: Never
      volumes:
      - name: license-volume
        hostPath:
          path: /home2/${USR}/2024_data/FREESURFER/.license
          type: File
      - name: data-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-${LBL}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: freesurfer-recon-all-job-${LBL}-${IDX4}
spec:
  template:
    spec:
      nodeSelector:
        key: ${LBL}
      containers:
      - name: freesurfer-container
        image: freesurfer/freesurfer:7.2.0
        command: ["/bin/bash", "-c", "mkdir -p /root/data/FREESURFER/FREESURFER_OUTDIR; source /usr/local/freesurfer/SetUpFreeSurfer.sh; recon-all -subjid ${IDX4} -i /root/data/FREESURFER/OUTDIR/${IDX4}.nii.gz -sd /root/data/FREESURFER/FREESURFER_OUTDIR -all"]
        resources:
          requests:
            cpu: "3800m"
          limits:
            cpu: "4000m"
        volumeMounts:
        - name: license-volume
          mountPath: /usr/local/freesurfer/.license
        - name: data-volume
          mountPath: /root/data
      restartPolicy: Never
      volumes:
      - name: license-volume
        hostPath:
          path: /home2/${USR}/2024_data/FREESURFER/.license
          type: File
      - name: data-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-${LBL}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: freesurfer-recon-all-job-${LBL}-${IDX5}
spec:
  template:
    spec:
      nodeSelector:
        key: ${LBL}
      containers:
      - name: freesurfer-container
        image: freesurfer/freesurfer:7.2.0
        command: ["/bin/bash", "-c", "mkdir -p /root/data/FREESURFER/FREESURFER_OUTDIR; source /usr/local/freesurfer/SetUpFreeSurfer.sh; recon-all -subjid ${IDX5} -i /root/data/FREESURFER/OUTDIR/${IDX5}.nii.gz -sd /root/data/FREESURFER/FREESURFER_OUTDIR -all"]
        resources:
          requests:
            cpu: "3800m"
          limits:
            cpu: "4000m"
        volumeMounts:
        - name: license-volume
          mountPath: /usr/local/freesurfer/.license
        - name: data-volume
          mountPath: /root/data
      restartPolicy: Never
      volumes:
      - name: license-volume
        hostPath:
          path: /home2/${USR}/2024_data/FREESURFER/.license
          type: File
      - name: data-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-${LBL}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: freesurfer-recon-all-job-${LBL}-${IDX6}
spec:
  template:
    spec:
      nodeSelector:
        key: ${LBL}
      containers:
      - name: freesurfer-container
        image: freesurfer/freesurfer:7.2.0
        command: ["/bin/bash", "-c", "mkdir -p /root/data/FREESURFER/FREESURFER_OUTDIR; source /usr/local/freesurfer/SetUpFreeSurfer.sh; recon-all -subjid ${IDX6} -i /root/data/FREESURFER/OUTDIR/${IDX6}.nii.gz -sd /root/data/FREESURFER/FREESURFER_OUTDIR -all"]
        resources:
          requests:
            cpu: "3800m"
          limits:
            cpu: "4000m"
        volumeMounts:
        - name: license-volume
          mountPath: /usr/local/freesurfer/.license
        - name: data-volume
          mountPath: /root/data
      restartPolicy: Never
      volumes:
      - name: license-volume
        hostPath:
          path: /home2/${USR}/2024_data/FREESURFER/.license
          type: File
      - name: data-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-${LBL}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: freesurfer-recon-all-job-${LBL}-${IDX7}
spec:
  template:
    spec:
      nodeSelector:
        key: ${LBL}
      containers:
      - name: freesurfer-container
        image: freesurfer/freesurfer:7.2.0
        command: ["/bin/bash", "-c", "mkdir -p /root/data/FREESURFER/FREESURFER_OUTDIR; source /usr/local/freesurfer/SetUpFreeSurfer.sh; recon-all -subjid ${IDX7} -i /root/data/FREESURFER/OUTDIR/${IDX7}.nii.gz -sd /root/data/FREESURFER/FREESURFER_OUTDIR -all"]
        resources:
          requests:
            cpu: "3800m"
          limits:
            cpu: "4000m"
        volumeMounts:
        - name: license-volume
          mountPath: /usr/local/freesurfer/.license
        - name: data-volume
          mountPath: /root/data
      restartPolicy: Never
      volumes:
      - name: license-volume
        hostPath:
          path: /home2/${USR}/2024_data/FREESURFER/.license
          type: File
      - name: data-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-${LBL}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: freesurfer-recon-all-job-${LBL}-${IDX8}
spec:
  template:
    spec:
      nodeSelector:
        key: ${LBL}
      containers:
      - name: freesurfer-container
        image: freesurfer/freesurfer:7.2.0
        command: ["/bin/bash", "-c", "mkdir -p /root/data/FREESURFER/FREESURFER_OUTDIR; source /usr/local/freesurfer/SetUpFreeSurfer.sh; recon-all -subjid ${IDX8} -i /root/data/FREESURFER/OUTDIR/${IDX8}.nii.gz -sd /root/data/FREESURFER/FREESURFER_OUTDIR -all"]
        resources:
          requests:
            cpu: "3800m"
          limits:
            cpu: "4000m"
        volumeMounts:
        - name: license-volume
          mountPath: /usr/local/freesurfer/.license
        - name: data-volume
          mountPath: /root/data
      restartPolicy: Never
      volumes:
      - name: license-volume
        hostPath:
          path: /home2/${USR}/2024_data/FREESURFER/.license
          type: File
      - name: data-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-${LBL}