---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freesurfer-license-pv-vd
  labels:
    type: freesurfer-license
    user: vd
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home2/dwnusa/2024_data/.license
    type: File
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freesurfer-license-pv-vj
  labels:
    type: freesurfer-license
    user: vj
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home2/jennyk0321/2024_data/.license
    type: File
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freesurfer-license-pv-vk
  labels:
    type: freesurfer-license
    user: vk
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home2/ksyint1111/2024_data/.license
    type: File
