apiVersion: v1
kind: Service
metadata:
  name: fedcuda-nodeport-vj
spec:
  type: NodePort
  selector:
    app: fedcuda-vj
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022
