apiVersion: v1
kind: Service
metadata:
  name: ssh-server-nodeport-vj
spec:
  type: NodePort
  selector:
    app: ssh-server-vj
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022
