apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedcuda-deployment-vd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fedcuda-vd
  template:
    metadata:
      labels:
        app: fedcuda-vd
    spec:
      nodeSelector:
        key: vd
      containers:
      - name: fedcuda-vd
        image: dwnusa/fedcuda:v0.1
        ports:
          - containerPort: 22
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: fedcuda-volume
          mountPath: /root/data
      volumes:
      - name: fedcuda-volume
        persistentVolumeClaim:
          claimName: fedcuda-pvc-vd
