apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedcuda-pvc-vd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: manual
  selector:
    matchLabels:
      type: local
