apiVersion: v1
kind: Service
metadata:
  name: fedcuda-nodeport-vd
spec:
  type: NodePort
  selector:
    app: fedcuda-vd
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30021
