apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-server-deployment-vd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssh-server-vd
  template:
    metadata:
      labels:
        app: ssh-server-vd
    spec:
      nodeSelector:
        key: vd
      containers:
      - name: ssh-server
        image: rastasheep/ubuntu-sshd
        ports:
          - containerPort: 22
